spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://aliyun:3306/sms?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: root
    
swagger:
  base-package:
    com.cbwleft.sms.controller
    
logging:
  level:
    com.cbwleft.sms: debug